### ISSUE TITLE
New features to Home page

### ISSUE THREAD

**Issue by AntwoneT** [LeighMcG83/marcos-mochas#1]
Home page needs new features added on to the structure of the HTML.
Features in mind would be...

1. (Fake) Address, business number & email which will be clickable link to the contact page.
2. Business logo at top (doesn't matter where at).
3. Double check that all spelling is correct.
4. Add some emojis to make the site creative
5. Add a COVID-19 alert and a way to make sure everyone is safe.

**Comment by LeighMcG83** [comment]
1. added fake Address, business number & email to footer of index.html
2. created and inserted bus. logo into header
3. spellchecked all index.html content
4. added emoji's as bullet points in index.html>brewingTips
5. Added covis warning sign and notification of restrictions in effect to index.html>header
